//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scenario.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Credit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Credit()
        {
            this.CreditTransitionMatrices = new HashSet<CreditTransitionMatrix>();
        }
    
        public int ID { get; internal set; }
        public double Pi { get; set; }
        public double Spread { get; set; }
        public double Price { get; set; }
        public int ConfigId { get; internal set; }
        public double SpreadAdj { get; set; }
        public Nullable<int> DefaultCreditId { get; set; }
    
        public virtual Configuration Configuration { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CreditTransitionMatrix> CreditTransitionMatrices { get; set; }
        public virtual DefaultCredit DefaultCredit { get; set; }
    }
}
