//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scenario.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CURVES_MC_1
    {
        public int ScenarioId { get; set; }
        public int Trial { get; set; }
        public int Timestep { get; set; }
        public double ZC_P_AAA__1y { get; set; }
        public double ZC_P_AAA__2y { get; set; }
        public double ZC_P_AAA__3y { get; set; }
        public double ZC_P_AAA__4y { get; set; }
        public double ZC_P_AAA__5y { get; set; }
        public double ZC_P_AAA__6y { get; set; }
        public double ZC_P_AAA__7y { get; set; }
        public double ZC_P_AAA__8y { get; set; }
        public double ZC_P_AAA__9y { get; set; }
        public double ZC_P_AAA__10y { get; set; }
        public double ZC_P_AAA__11y { get; set; }
        public double ZC_P_AAA__12y { get; set; }
        public double ZC_P_AAA__13y { get; set; }
        public double ZC_P_AAA__14y { get; set; }
        public double ZC_P_AAA__15y { get; set; }
        public double ZC_P_AAA__16y { get; set; }
        public double ZC_P_AAA__17y { get; set; }
        public double ZC_P_AAA__18y { get; set; }
        public double ZC_P_AAA__19y { get; set; }
        public double ZC_P_AAA__20y { get; set; }
        public double ZC_P_AAA__21y { get; set; }
        public double ZC_P_AAA__22y { get; set; }
        public double ZC_P_AAA__23y { get; set; }
        public double ZC_P_AAA__24y { get; set; }
        public double ZC_P_AAA__25y { get; set; }
        public double ZC_P_AAA__26y { get; set; }
        public double ZC_P_AAA__27y { get; set; }
        public double ZC_P_AAA__28y { get; set; }
        public double ZC_P_AAA__29y { get; set; }
        public double ZC_P_AAA__30y { get; set; }
        public double ZC_P_AAA__31y { get; set; }
        public double ZC_P_AAA__32y { get; set; }
        public double ZC_P_AAA__33y { get; set; }
        public double ZC_P_AAA__34y { get; set; }
        public double ZC_P_AAA__35y { get; set; }
        public double ZC_P_AAA__36y { get; set; }
        public double ZC_P_AAA__37y { get; set; }
        public double ZC_P_AAA__38y { get; set; }
        public double ZC_P_AAA__39y { get; set; }
        public double ZC_P_AAA__40y { get; set; }
        public double ZC_P_AAA__41y { get; set; }
        public double ZC_P_AAA__42y { get; set; }
        public double ZC_P_AAA__43y { get; set; }
        public double ZC_P_AAA__44y { get; set; }
        public double ZC_P_AAA__45y { get; set; }
        public double ZC_P_AAA__46y { get; set; }
        public double ZC_P_AAA__47y { get; set; }
        public double ZC_P_AAA__48y { get; set; }
        public double ZC_P_AAA__49y { get; set; }
        public double ZC_P_AAA__50y { get; set; }
        public double ZC_P_AAA__51y { get; set; }
        public double ZC_P_AAA__52y { get; set; }
        public double ZC_P_AAA__53y { get; set; }
        public double ZC_P_AAA__54y { get; set; }
        public double ZC_P_AAA__55y { get; set; }
        public double ZC_P_AAA__56y { get; set; }
        public double ZC_P_AAA__57y { get; set; }
        public double ZC_P_AAA__58y { get; set; }
        public double ZC_P_AAA__59y { get; set; }
        public double ZC_P_AAA__60y { get; set; }
        public double ZC_P_AA__1y { get; set; }
        public double ZC_P_AA__2y { get; set; }
        public double ZC_P_AA__3y { get; set; }
        public double ZC_P_AA__4y { get; set; }
        public double ZC_P_AA__5y { get; set; }
        public double ZC_P_AA__6y { get; set; }
        public double ZC_P_AA__7y { get; set; }
        public double ZC_P_AA__8y { get; set; }
        public double ZC_P_AA__9y { get; set; }
        public double ZC_P_AA__10y { get; set; }
        public double ZC_P_AA__11y { get; set; }
        public double ZC_P_AA__12y { get; set; }
        public double ZC_P_AA__13y { get; set; }
        public double ZC_P_AA__14y { get; set; }
        public double ZC_P_AA__15y { get; set; }
        public double ZC_P_AA__16y { get; set; }
        public double ZC_P_AA__17y { get; set; }
        public double ZC_P_AA__18y { get; set; }
        public double ZC_P_AA__19y { get; set; }
        public double ZC_P_AA__20y { get; set; }
        public double ZC_P_AA__21y { get; set; }
        public double ZC_P_AA__22y { get; set; }
        public double ZC_P_AA__23y { get; set; }
        public double ZC_P_AA__24y { get; set; }
        public double ZC_P_AA__25y { get; set; }
        public double ZC_P_AA__26y { get; set; }
        public double ZC_P_AA__27y { get; set; }
        public double ZC_P_AA__28y { get; set; }
        public double ZC_P_AA__29y { get; set; }
        public double ZC_P_AA__30y { get; set; }
        public double ZC_P_AA__31y { get; set; }
        public double ZC_P_AA__32y { get; set; }
        public double ZC_P_AA__33y { get; set; }
        public double ZC_P_AA__34y { get; set; }
        public double ZC_P_AA__35y { get; set; }
        public double ZC_P_AA__36y { get; set; }
        public double ZC_P_AA__37y { get; set; }
        public double ZC_P_AA__38y { get; set; }
        public double ZC_P_AA__39y { get; set; }
        public double ZC_P_AA__40y { get; set; }
        public double ZC_P_AA__41y { get; set; }
        public double ZC_P_AA__42y { get; set; }
        public double ZC_P_AA__43y { get; set; }
        public double ZC_P_AA__44y { get; set; }
        public double ZC_P_AA__45y { get; set; }
        public double ZC_P_AA__46y { get; set; }
        public double ZC_P_AA__47y { get; set; }
        public double ZC_P_AA__48y { get; set; }
        public double ZC_P_AA__49y { get; set; }
        public double ZC_P_AA__50y { get; set; }
        public double ZC_P_AA__51y { get; set; }
        public double ZC_P_AA__52y { get; set; }
        public double ZC_P_AA__53y { get; set; }
        public double ZC_P_AA__54y { get; set; }
        public double ZC_P_AA__55y { get; set; }
        public double ZC_P_AA__56y { get; set; }
        public double ZC_P_AA__57y { get; set; }
        public double ZC_P_AA__58y { get; set; }
        public double ZC_P_AA__59y { get; set; }
        public double ZC_P_AA__60y { get; set; }
        public double ZC_P_A__1y { get; set; }
        public double ZC_P_A__2y { get; set; }
        public double ZC_P_A__3y { get; set; }
        public double ZC_P_A__4y { get; set; }
        public double ZC_P_A__5y { get; set; }
        public double ZC_P_A__6y { get; set; }
        public double ZC_P_A__7y { get; set; }
        public double ZC_P_A__8y { get; set; }
        public double ZC_P_A__9y { get; set; }
        public double ZC_P_A__10y { get; set; }
        public double ZC_P_A__11y { get; set; }
        public double ZC_P_A__12y { get; set; }
        public double ZC_P_A__13y { get; set; }
        public double ZC_P_A__14y { get; set; }
        public double ZC_P_A__15y { get; set; }
        public double ZC_P_A__16y { get; set; }
        public double ZC_P_A__17y { get; set; }
        public double ZC_P_A__18y { get; set; }
        public double ZC_P_A__19y { get; set; }
        public double ZC_P_A__20y { get; set; }
        public double ZC_P_A__21y { get; set; }
        public double ZC_P_A__22y { get; set; }
        public double ZC_P_A__23y { get; set; }
        public double ZC_P_A__24y { get; set; }
        public double ZC_P_A__25y { get; set; }
        public double ZC_P_A__26y { get; set; }
        public double ZC_P_A__27y { get; set; }
        public double ZC_P_A__28y { get; set; }
        public double ZC_P_A__29y { get; set; }
        public double ZC_P_A__30y { get; set; }
        public double ZC_P_A__31y { get; set; }
        public double ZC_P_A__32y { get; set; }
        public double ZC_P_A__33y { get; set; }
        public double ZC_P_A__34y { get; set; }
        public double ZC_P_A__35y { get; set; }
        public double ZC_P_A__36y { get; set; }
        public double ZC_P_A__37y { get; set; }
        public double ZC_P_A__38y { get; set; }
        public double ZC_P_A__39y { get; set; }
        public double ZC_P_A__40y { get; set; }
        public double ZC_P_A__41y { get; set; }
        public double ZC_P_A__42y { get; set; }
        public double ZC_P_A__43y { get; set; }
        public double ZC_P_A__44y { get; set; }
        public double ZC_P_A__45y { get; set; }
        public double ZC_P_A__46y { get; set; }
        public double ZC_P_A__47y { get; set; }
        public double ZC_P_A__48y { get; set; }
        public double ZC_P_A__49y { get; set; }
        public double ZC_P_A__50y { get; set; }
        public double ZC_P_A__51y { get; set; }
        public double ZC_P_A__52y { get; set; }
        public double ZC_P_A__53y { get; set; }
        public double ZC_P_A__54y { get; set; }
        public double ZC_P_A__55y { get; set; }
        public double ZC_P_A__56y { get; set; }
        public double ZC_P_A__57y { get; set; }
        public double ZC_P_A__58y { get; set; }
        public double ZC_P_A__59y { get; set; }
        public double ZC_P_A__60y { get; set; }
        public Nullable<bool> Exported { get; set; }
    
        public virtual Configuration Configuration { get; set; }
    }
}
