//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scenario.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DefaultCredit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DefaultCredit()
        {
            this.Credits = new HashSet<Credit>();
        }
    
        public int ID { get; set; }
        public System.DateTime Date { get; set; }
        public double Maturity { get; set; }
        public double Spread { get; set; }
        public string Rating { get; set; }
        public string Economy { get; set; }
        public double RecoveryRate { get; set; }
        public int Seniority { get; set; }
        public int Version { get; set; }
        public double Percentage { get; set; }
        public string Type { get; set; }
        public double Adjustment { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Credit> Credits { get; set; }
    }
}
