//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scenario.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXTRA
    {
        public int ScenarioId { get; set; }
        public int Trial { get; set; }
        public int Timestep { get; set; }
        public Nullable<double> PCapitalChange { get; set; }
        public Nullable<double> P2CapitalChange { get; set; }
        public double NShortRate { get; set; }
        public Nullable<double> ZScore { get; set; }
        public double AAATotalReturn { get; set; }
        public double AATotalReturn { get; set; }
        public double ATotalReturn { get; set; }
        public double BBBTotalReturn { get; set; }
        public double BBTotalReturn { get; set; }
        public double BTotalReturn { get; set; }
        public double CCCTotalReturn { get; set; }
        public double RShortRate { get; set; }
        public Nullable<bool> Exported { get; set; }
        public double DecorrelatedZScore { get; set; }
        public Nullable<double> ExchangeRateR { get; set; }
        public Nullable<double> ExchangeRateN { get; set; }
        public double CreditRPIntegrated { get; set; }
    
        public virtual Configuration Configuration { get; set; }
    }
}
