//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scenario.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factor
    {
        public double B1 { get; set; }
        public double B2 { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public int Index { get; set; }
        public Nullable<int> GID { get; set; }
        public int ID { get; set; }
    
        public virtual ModelsFactor ModelsFactor { get; set; }
    }
}
