//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scenario.Entities
{
    using System;
    using System.Collections.Generic;
    
    public abstract partial class Model
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Model()
        {
            this.ModelParameters = new HashSet<ModelParameter>();
            this.ScenarioTypes = new HashSet<ScenarioType>();
        }
    
        public int Id { get; set; }
        internal int Equit { get; set; }
        internal int Propert { get; set; }
        internal int NYC_ { get; set; }
        internal int RYC_ { get; set; }
        internal int Credit_ { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ModelParameter> ModelParameters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScenarioType> ScenarioTypes { get; set; }
        public virtual ModelTemplate Credit { get; set; }
        public virtual ModelTemplate Equity { get; set; }
        public virtual ModelTemplate NYC { get; set; }
        public virtual ModelTemplate Property { get; set; }
        public virtual ModelTemplate RYC { get; set; }
    }
}
