//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scenario.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModelParameter
    {
        public double s0 { get; set; }
        public double sinf { get; set; }
        public double a { get; set; }
        public double r0 { get; set; }
        public double m0 { get; set; }
        public double g { get; set; }
        public double m { get; set; }
        public double ra1 { get; set; }
        public double ra2 { get; set; }
        public double rs1 { get; set; }
        public double rs2 { get; set; }
        public double na1 { get; set; }
        public double na2 { get; set; }
        public double ns1 { get; set; }
        public double ns2 { get; set; }
        public int ConfigurationId { get; internal set; }
        public double sesReal1 { get; set; }
        public double sesReal2 { get; set; }
        public int ModelsId { get; set; }
        public double LMMPlus_a { get; set; }
        public double LMMPlus_b { get; set; }
        public double LMMPlus_c { get; set; }
        public double LMMPlusVolInit { get; set; }
        public double LMMPlusRevRate { get; set; }
        public double LMMPlusRevLevel { get; set; }
        public double LMMPlusVol { get; set; }
        public double LMMPlusVolCorr { get; set; }
        public double LMMPlusRateDispl { get; set; }
        public double LMMPlus_d { get; set; }
        public double SVJDVolInit { get; set; }
        public double SVJDRevLevel { get; set; }
        public double SVJDRevSpeed { get; set; }
        public double SVJDVol { get; set; }
        public double SVJDCOrr { get; set; }
        public double SVJDJumpArrivalRate { get; set; }
        public double SVJDJumpMean { get; set; }
        public double SVJDJumpVol { get; set; }
        public double ExchangeRateMu { get; set; }
        public double ExchangeRateStart { get; set; }
        public double ExchangeRateVol { get; set; }
        public Nullable<int> FactorsGID { get; set; }
        public Nullable<int> SwaptionsGID { get; set; }
        public int ExecutedCalibrations { get; set; }
        public double nCap { get; set; }
        public double nFloor { get; set; }
        public double nFreezeUpper { get; set; }
        public double nFreezeLower { get; set; }
        public int nBounding { get; set; }
    
        public virtual Configuration Configuration { get; set; }
        public virtual Model Models { get; set; }
        public virtual ModelsFactor ModelsFactor { get; set; }
        public virtual SwaptionCurve SwaptionCurve { get; set; }
    }
}
