//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scenario.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class REALC
    {
        public int ScenarioId { get; set; }
        public int Trial { get; set; }
        public int Timestep { get; set; }
        public double ZC_P_Real__1y { get; set; }
        public double ZC_P_Real__2y { get; set; }
        public double ZC_P_Real__3y { get; set; }
        public double ZC_P_Real__4y { get; set; }
        public double ZC_P_Real__5y { get; set; }
        public double ZC_P_Real__6y { get; set; }
        public double ZC_P_Real__7y { get; set; }
        public double ZC_P_Real__8y { get; set; }
        public double ZC_P_Real__9y { get; set; }
        public double ZC_P_Real__10y { get; set; }
        public double ZC_P_Real__11y { get; set; }
        public double ZC_P_Real__12y { get; set; }
        public double ZC_P_Real__13y { get; set; }
        public double ZC_P_Real__14y { get; set; }
        public double ZC_P_Real__15y { get; set; }
        public double ZC_P_Real__16y { get; set; }
        public double ZC_P_Real__17y { get; set; }
        public double ZC_P_Real__18y { get; set; }
        public double ZC_P_Real__19y { get; set; }
        public double ZC_P_Real__20y { get; set; }
        public double ZC_P_Real__21y { get; set; }
        public double ZC_P_Real__22y { get; set; }
        public double ZC_P_Real__23y { get; set; }
        public double ZC_P_Real__24y { get; set; }
        public double ZC_P_Real__25y { get; set; }
        public double ZC_P_Real__26y { get; set; }
        public double ZC_P_Real__27y { get; set; }
        public double ZC_P_Real__28y { get; set; }
        public double ZC_P_Real__29y { get; set; }
        public double ZC_P_Real__30y { get; set; }
        public double ZC_P_Real__31y { get; set; }
        public double ZC_P_Real__32y { get; set; }
        public double ZC_P_Real__33y { get; set; }
        public double ZC_P_Real__34y { get; set; }
        public double ZC_P_Real__35y { get; set; }
        public double ZC_P_Real__36y { get; set; }
        public double ZC_P_Real__37y { get; set; }
        public double ZC_P_Real__38y { get; set; }
        public double ZC_P_Real__39y { get; set; }
        public double ZC_P_Real__40y { get; set; }
        public double ZC_P_Real__41y { get; set; }
        public double ZC_P_Real__42y { get; set; }
        public double ZC_P_Real__43y { get; set; }
        public double ZC_P_Real__44y { get; set; }
        public double ZC_P_Real__45y { get; set; }
        public double ZC_P_Real__46y { get; set; }
        public double ZC_P_Real__47y { get; set; }
        public double ZC_P_Real__48y { get; set; }
        public double ZC_P_Real__49y { get; set; }
        public double ZC_P_Real__50y { get; set; }
        public double ZC_P_Real__51y { get; set; }
        public double ZC_P_Real__52y { get; set; }
        public double ZC_P_Real__53y { get; set; }
        public double ZC_P_Real__54y { get; set; }
        public double ZC_P_Real__55y { get; set; }
        public double ZC_P_Real__56y { get; set; }
        public double ZC_P_Real__57y { get; set; }
        public double ZC_P_Real__58y { get; set; }
        public double ZC_P_Real__59y { get; set; }
        public double ZC_P_Real__60y { get; set; }
        public Nullable<bool> Exported { get; set; }
    
        public virtual Configuration Configuration { get; set; }
    }
}
