//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scenario.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScenarioSummary
    {
        public System.DateTime Date { get; set; }
        public string Type { get; set; }
        public string Description { get; set; }
        public string TypeEconomy { get; set; }
        public string Economy { get; set; }
        public string Country { get; set; }
        public int Version { get; set; }
        public string TypeDescription { get; set; }
        public int ID { get; set; }
        public Nullable<int> ParentId { get; set; }
        internal int Status { get; set; }
    }
}
