//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scenario.Entities
{
    using System;
    using System.Collections.Generic;
    
    public abstract partial class ScenarioType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ScenarioType()
        {
            this.Configurations = new HashSet<Configuration>();
        }
    
        public System.DateTime ScenarioDate { get; internal set; }
        public System.DateTime DueDate { get; internal set; }
        public string Description { get; internal set; }
        public string Economy { get; internal set; }
        public int Swap { get; internal set; }
        internal int ID { get; set; }
        public string TransitionMatrixType { get; internal set; }
        public int ModelId { get; set; }
        public string Country { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Configuration> Configurations { get; set; }
        public virtual Model DefaultModel { get; set; }
    }
}
