//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scenario.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUMMARY
    {
        public int ScenarioId { get; set; }
        public int Trial { get; set; }
        public int Timestep { get; set; }
        public double DEFLATOR { get; set; }
        public double CASH_TOTRET { get; set; }
        public double EQUITY_TOTRET { get; set; }
        public double EQUITY_DIVYIELD { get; set; }
        public double PROPERTY_TOTRET { get; set; }
        public double PROPERTY_INCOMERET { get; set; }
        public Nullable<double> PROPERTY2_TOTRET { get; set; }
        public Nullable<double> PROPERTY2_INCOMERET { get; set; }
        public double INFLATIONRATE { get; set; }
        public double ZC_P_Govt__1y { get; set; }
        public double ZC_P_Govt__2y { get; set; }
        public double ZC_P_Govt__3y { get; set; }
        public double ZC_P_Govt__4y { get; set; }
        public double ZC_P_Govt__5y { get; set; }
        public double ZC_P_Govt__6y { get; set; }
        public double ZC_P_Govt__7y { get; set; }
        public double ZC_P_Govt__8y { get; set; }
        public double ZC_P_Govt__9y { get; set; }
        public double ZC_P_Govt__10y { get; set; }
        public double ZC_P_Govt__11y { get; set; }
        public double ZC_P_Govt__12y { get; set; }
        public double ZC_P_Govt__13y { get; set; }
        public double ZC_P_Govt__14y { get; set; }
        public double ZC_P_Govt__15y { get; set; }
        public double ZC_P_Govt__16y { get; set; }
        public double ZC_P_Govt__17y { get; set; }
        public double ZC_P_Govt__18y { get; set; }
        public double ZC_P_Govt__19y { get; set; }
        public double ZC_P_Govt__20y { get; set; }
        public double ZC_P_Govt__21y { get; set; }
        public double ZC_P_Govt__22y { get; set; }
        public double ZC_P_Govt__23y { get; set; }
        public double ZC_P_Govt__24y { get; set; }
        public double ZC_P_Govt__25y { get; set; }
        public double ZC_P_Govt__26y { get; set; }
        public double ZC_P_Govt__27y { get; set; }
        public double ZC_P_Govt__28y { get; set; }
        public double ZC_P_Govt__29y { get; set; }
        public double ZC_P_Govt__30y { get; set; }
        public double ZC_P_Govt__31y { get; set; }
        public double ZC_P_Govt__32y { get; set; }
        public double ZC_P_Govt__33y { get; set; }
        public double ZC_P_Govt__34y { get; set; }
        public double ZC_P_Govt__35y { get; set; }
        public double ZC_P_Govt__36y { get; set; }
        public double ZC_P_Govt__37y { get; set; }
        public double ZC_P_Govt__38y { get; set; }
        public double ZC_P_Govt__39y { get; set; }
        public double ZC_P_Govt__40y { get; set; }
        public double ZC_P_Govt__41y { get; set; }
        public double ZC_P_Govt__42y { get; set; }
        public double ZC_P_Govt__43y { get; set; }
        public double ZC_P_Govt__44y { get; set; }
        public double ZC_P_Govt__45y { get; set; }
        public double ZC_P_Govt__46y { get; set; }
        public double ZC_P_Govt__47y { get; set; }
        public double ZC_P_Govt__48y { get; set; }
        public double ZC_P_Govt__49y { get; set; }
        public double ZC_P_Govt__50y { get; set; }
        public double ZC_P_Govt__51y { get; set; }
        public double ZC_P_Govt__52y { get; set; }
        public double ZC_P_Govt__53y { get; set; }
        public double ZC_P_Govt__54y { get; set; }
        public double ZC_P_Govt__55y { get; set; }
        public double ZC_P_Govt__56y { get; set; }
        public double ZC_P_Govt__57y { get; set; }
        public double ZC_P_Govt__58y { get; set; }
        public double ZC_P_Govt__59y { get; set; }
        public double ZC_P_Govt__60y { get; set; }
        public Nullable<bool> Exported { get; set; }
    
        public virtual Configuration Configuration { get; set; }
    }
}
