//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scenario.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANSITION_MATRIX
    {
        public int ScenarioId { get; set; }
        public int Trial { get; set; }
        public int Timestep { get; set; }
        public double AAA_to_AAA { get; set; }
        public double AAA_to_AA { get; set; }
        public double AAA_to_A { get; set; }
        public double AAA_to_BBB { get; set; }
        public double AAA_to_BB { get; set; }
        public double AAA_to_B { get; set; }
        public double AAA_to_CCC { get; set; }
        public double AAA_to_Default { get; set; }
        public double AA_to_AAA { get; set; }
        public double AA_to_AA { get; set; }
        public double AA_to_A { get; set; }
        public double AA_to_BBB { get; set; }
        public double AA_to_BB { get; set; }
        public double AA_to_B { get; set; }
        public double AA_to_CCC { get; set; }
        public double AA_to_Default { get; set; }
        public double A_to_AAA { get; set; }
        public double A_to_AA { get; set; }
        public double A_to_A { get; set; }
        public double A_to_BBB { get; set; }
        public double A_to_BB { get; set; }
        public double A_to_B { get; set; }
        public double A_to_CCC { get; set; }
        public double A_to_Default { get; set; }
        public double BBB_to_AAA { get; set; }
        public double BBB_to_AA { get; set; }
        public double BBB_to_A { get; set; }
        public double BBB_to_BBB { get; set; }
        public double BBB_to_BB { get; set; }
        public double BBB_to_B { get; set; }
        public double BBB_to_CCC { get; set; }
        public double BBB_to_Default { get; set; }
        public double BB_to_AAA { get; set; }
        public double BB_to_AA { get; set; }
        public double BB_to_A { get; set; }
        public double BB_to_BBB { get; set; }
        public double BB_to_BB { get; set; }
        public double BB_to_B { get; set; }
        public double BB_to_CCC { get; set; }
        public double BB_to_Default { get; set; }
        public double B_to_AAA { get; set; }
        public double B_to_AA { get; set; }
        public double B_to_A { get; set; }
        public double B_to_BBB { get; set; }
        public double B_to_BB { get; set; }
        public double B_to_B { get; set; }
        public double B_to_CCC { get; set; }
        public double B_to_Default { get; set; }
        public double CCC_to_AAA { get; set; }
        public double CCC_to_AA { get; set; }
        public double CCC_to_A { get; set; }
        public double CCC_to_BBB { get; set; }
        public double CCC_to_BB { get; set; }
        public double CCC_to_B { get; set; }
        public double CCC_to_CCC { get; set; }
        public double CCC_to_Default { get; set; }
        public Nullable<bool> Exported { get; set; }
    
        public virtual Configuration Configuration { get; set; }
    }
}
